### PR TITLE
Fix setting up boinc projects

### PR DESCRIPTION
**Pull request by dcz-mpipz**
This brings the project back to runnable state again.

### CODE REVIEW

**Comment by groggemans** [comment]
@dcz-mpipz I'm no longer actively maintaining this role. (Hence the deprecation warning in the README)

Because this is still the only BOINC ansible role on galaxy, I'm willing to support it again, but won't actively work on it.

Can you tell me more about your use-case? Are you willing to actively work on this role/maintain it?

**Comment by dcz-mpipz** [comment]
These changes were just to make it work in order to see if it's useful.

I'm unlikely to maintain it, but I opened this PR to make sure people can find a working version.

**Comment by groggemans** [comment]
Ok, Thank you for the PR

Virtualbox was needed for all projects I ran on BOINC, don't you need this? Did it fail to install? And on which OS? (the virtualbox package probably has another name or isn't available)

I'll probably do a little update later to make this more configurable.

**Comment by dcz-mpipz** [comment]
I could run https://milkyway.cs.rpi.edu/milkyway/ just fine, however things like http://www.gpugrid.net/ don't even start for some reason.

I only tested on Debian 9 (stretch), where `virtualbox` isn't provided in the default repositories.

**Comment by groggemans** [comment]
Ok, thx for the info.

I'll probably release the new version later this evening (CET).

**Pull request merged**
